### ISSUE TITLE
Splunk indexer should be able to accept an array of parameters

### ISSUE THREAD

**Issue by basepi** [hubblestack/hubble-salt#21]
_From @zxjinn on September 13, 2016 22:1_

For Pulsar and Nova, but this error is just for Nova

When specifying an array of indexers it throws an error

```
[INFO    ] Options: {"index": "hubble_audit", "token": "TOOOP-SEEC-REET-TOE-KENNNNN", "sourcetype": "hubble_audit", "indexer": ["hostname1.fqdn.tld", "hostname2.fqdn.tld"]}
[ERROR   ] Unhandled exception running hubble.audit
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/utils/schedule.py", line 557, in handle_func
    self.returners[ret_str](ret)
  File "/var/cache/salt/minion/extmods/returners/splunk_nova_return.py", line 49, in returner
    hec = http_event_collector(http_event_collector_key, http_event_collector_host)
  File "/var/cache/salt/minion/extmods/returners/splunk_nova_return.py", line 204, in __init__
    self.server_uri = "".join(buildURI)
TypeError: sequence item 1: expected string, list found
```

I would expect it to jump randomly between all entries for load balancing, until one is found that works (doesn't timeout or otherwise throw an error).

_Copied from original issue: hubblestack/quasar#23_

**Comment by basepi** [comment]
That seems like a useful feature. We'll get it added.

**Comment by basepi** [comment]
_From @zxjinn on September 16, 2016 16:53_

Just thinking about how we'd implement it. An array would be awesome, but I hope a comma separated list would also work! Thanks

**Comment by basepi** [comment]
It's easy enough to support either. Thanks for the update.

**Comment by basepi** [comment]
A similar feature was added in https://github.com/hubblestack/hubble/pull/34, and since we have load balancing on our splunk heavy forwarders I don't think this is necessary at the moment. I'm going to close this for now unless anyone has objections.
